/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { ApiGamesGetCollection200SearchMappingItemProperty } from './apiGamesGetCollection200SearchMappingItemProperty';

export type ApiGamesGetCollection200SearchMappingItem = {
  '@type'?: string;
  variable?: string;
  property?: ApiGamesGetCollection200SearchMappingItemProperty;
  required?: boolean;
};
