/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { ApiGamesGetCollection200OneSearchMappingItem } from './apiGamesGetCollection200OneSearchMappingItem';

export type ApiGamesGetCollection200OneSearch = {
  '@type'?: string;
  template?: string;
  variableRepresentation?: string;
  mapping?: ApiGamesGetCollection200OneSearchMappingItem[];
};
