/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { GameJsonldGamesUserRead } from './gameJsonldGamesUserRead';
import type { ApiGamesGetCollection200OneView } from './apiGamesGetCollection200OneView';
import type { ApiGamesGetCollection200OneSearch } from './apiGamesGetCollection200OneSearch';

export type ApiGamesGetCollection200One = {
  member: GameJsonldGamesUserRead[];
  /** @minimum 0 */
  totalItems?: number;
  view?: ApiGamesGetCollection200OneView;
  search?: ApiGamesGetCollection200OneSearch;
};
