/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { GameJsonldGamesUserRead } from './gameJsonldGamesUserRead';
import type { ApiGamesGetCollection200View } from './apiGamesGetCollection200View';
import type { ApiGamesGetCollection200Search } from './apiGamesGetCollection200Search';

export type ApiGamesGetCollection200 = {
  member: GameJsonldGamesUserRead[];
  /** @minimum 0 */
  totalItems?: number;
  view?: ApiGamesGetCollection200View;
  search?: ApiGamesGetCollection200Search;
};
