/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { ApiGamesGetCollection200OneSearchMappingItemProperty } from './apiGamesGetCollection200OneSearchMappingItemProperty';

export type ApiGamesGetCollection200OneSearchMappingItem = {
  '@type'?: string;
  variable?: string;
  property?: ApiGamesGetCollection200OneSearchMappingItemProperty;
  required?: boolean;
};
