/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

export type ApiGamesGetCollection200View = {
  '@id'?: string;
  '@type'?: string;
  first?: string;
  last?: string;
  previous?: string;
  next?: string;
};
