/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { ConstraintViolationJsonViolationsItem } from './constraintViolationJsonViolationsItem';
import type { ConstraintViolationJsonTitle } from './constraintViolationJsonTitle';
import type { ConstraintViolationJsonInstance } from './constraintViolationJsonInstance';

/**
 * Unprocessable entity
 */
export interface ConstraintViolationJson {
  status?: number;
  violations?: ConstraintViolationJsonViolationsItem[];
  readonly detail?: string;
  readonly type?: string;
  readonly title?: ConstraintViolationJsonTitle;
  readonly instance?: ConstraintViolationJsonInstance;
}
