/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { ConstraintViolationJsonldJsonldContextOneOfHydra } from './constraintViolationJsonldJsonldContextOneOfHydra';

export type ConstraintViolationJsonldJsonldContextOneOf = {
  '@vocab': string;
  hydra: ConstraintViolationJsonldJsonldContextOneOfHydra;
  [key: string]: unknown;
 };
