/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

export type ConstraintViolationJsonViolationsItem = {
  /** The property path of the violation */
  propertyPath?: string;
  /** The message associated with the violation */
  message?: string;
};
