/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorTitle } from './errorTitle';
import type { ErrorDetail } from './errorDetail';
import type { ErrorInstance } from './errorInstance';

/**
 * A representation of common errors.
 */
export interface Error {
  /** A short, human-readable summary of the problem. */
  readonly title?: ErrorTitle;
  /** A human-readable explanation specific to this occurrence of the problem. */
  readonly detail?: ErrorDetail;
  status?: number;
  /** A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
  readonly instance?: ErrorInstance;
  /** A URI reference that identifies the problem type */
  readonly type?: string;
}
