/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

/**
 * A human-readable explanation specific to this occurrence of the problem.
 */
export type ErrorDetail = string | null;
