/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

/**
 * A short, human-readable summary of the problem.
 */
export type ErrorTitle = string | null;
