/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorJsonldContext } from './errorJsonldContext';
import type { ErrorJsonldTitle } from './errorJsonldTitle';
import type { ErrorJsonldDetail } from './errorJsonldDetail';
import type { ErrorJsonldInstance } from './errorJsonldInstance';
import type { ErrorJsonldDescription } from './errorJsonldDescription';

/**
 * A representation of common errors.
 */
export interface ErrorJsonld {
  readonly '@context'?: ErrorJsonldContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  /** A short, human-readable summary of the problem. */
  readonly title?: ErrorJsonldTitle;
  /** A human-readable explanation specific to this occurrence of the problem. */
  readonly detail?: ErrorJsonldDetail;
  status?: number;
  /** A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
  readonly instance?: ErrorJsonldInstance;
  /** A URI reference that identifies the problem type */
  readonly type?: string;
  readonly description?: ErrorJsonldDescription;
}
