/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

/**
 * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
 */
export type ErrorInstance = string | null;
