/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorJsonldContextOneOf } from './errorJsonldContextOneOf';

export type ErrorJsonldContext = string | ErrorJsonldContextOneOf;
