/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { GameLevelJsonldGamesUserReadContextOneOfHydra } from './gameLevelJsonldGamesUserReadContextOneOfHydra';

export type GameLevelJsonldGamesUserReadContextOneOf = {
  '@vocab': string;
  hydra: GameLevelJsonldGamesUserReadContextOneOfHydra;
  [key: string]: unknown;
 };
