/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { GameJsonldGamesUserReadEndDateTime } from './gameJsonldGamesUserReadEndDateTime';
import type { GameLevelJsonldGamesUserRead } from './gameLevelJsonldGamesUserRead';

export interface GameJsonldGamesUserRead {
  readonly '@id'?: string;
  readonly '@type'?: string;
  startDateTime?: string;
  endDateTime?: GameJsonldGamesUserReadEndDateTime;
  hash?: string;
  gameLevels?: GameLevelJsonldGamesUserRead[];
  lives?: number;
}
