/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { GameGamesUserReadEndDateTime } from './gameGamesUserReadEndDateTime';
import type { GameLevelGamesUserRead } from './gameLevelGamesUserRead';

export interface GameGamesUserRead {
  startDateTime?: string;
  endDateTime?: GameGamesUserReadEndDateTime;
  hash?: string;
  gameLevels?: GameLevelGamesUserRead[];
  lives?: number;
}
