/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { GameJsonldGameReadContext } from './gameJsonldGameReadContext';
import type { GameJsonldGameReadEndDateTime } from './gameJsonldGameReadEndDateTime';
import type { GameLevelJsonldGameRead } from './gameLevelJsonldGameRead';

export interface GameJsonldGameRead {
  readonly '@context'?: GameJsonldGameReadContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  startDateTime?: string;
  endDateTime?: GameJsonldGameReadEndDateTime;
  hash?: string;
  gameLevels?: GameLevelJsonldGameRead[];
  lives?: number;
}
