/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

export type GameLevelJsonldGameReadContextOneOfHydra = typeof GameLevelJsonldGameReadContextOneOfHydra[keyof typeof GameLevelJsonldGameReadContextOneOfHydra];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameLevelJsonldGameReadContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const;
