/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

export interface Register {
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
}
