/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

export interface UserUserRead {
  readonly id?: number;
  email: string;
  firstName: string;
  lastName: string;
}
