/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { UserJsonldUserReadContextOneOfHydra } from './userJsonldUserReadContextOneOfHydra';

export type UserJsonldUserReadContextOneOf = {
  '@vocab': string;
  hydra: UserJsonldUserReadContextOneOfHydra;
  [key: string]: unknown;
 };
