/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { UserJsonldUserReadContext } from './userJsonldUserReadContext';

export interface UserJsonldUserRead {
  readonly '@context'?: UserJsonldUserReadContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  readonly id?: number;
  email: string;
  firstName: string;
  lastName: string;
}
