/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { WordJsonldGamesUserReadContextOneOfHydra } from './wordJsonldGamesUserReadContextOneOfHydra';

export type WordJsonldGamesUserReadContextOneOf = {
  '@vocab': string;
  hydra: WordJsonldGamesUserReadContextOneOfHydra;
  [key: string]: unknown;
 };
