/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */

export type WordJsonldGamesUserReadContextOneOfHydra = typeof WordJsonldGamesUserReadContextOneOfHydra[keyof typeof WordJsonldGamesUserReadContextOneOfHydra];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WordJsonldGamesUserReadContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const;
