/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Hackman Api
 * Hackman Api
 * OpenAPI spec version: 1.0.0
 */
import type { WordGameReadIv } from './wordGameReadIv';

export interface WordGameRead {
  readonly id?: number;
  word?: string;
  level?: number;
  hint?: string;
  iv?: WordGameReadIv;
}
